// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OncoTargetExplorer.Api.Data;

#nullable disable

namespace OncoTargetExplorer.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812101501_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("OncoTargetExplorer.Api.Data.ShortlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Accession")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProteinName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Accession")
                        .IsUnique();

                    b.ToTable("ShortlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
